rabbit1:
  image: hpess/rabbitmq 
  hostname: rabbit1
  ports:
    - "5672:5672"
    - "15672:15672"

rabbit2:
  image: hpess/rabbitmq 
  hostname: rabbit2
  links:
    - rabbit1
  environment: 
   - CLUSTERED=true
   - CLUSTERED_WITH=rabbit1
   - RAM_NODE=true
  ports:
    - "5673:5672"
    - "15673:15672"

rabbit3:
  image: hpess/rabbitmq 
  hostname: rabbit3
  links:
    - rabbit1
    - rabbit2
  environment: 
   - CLUSTERED=true
   - CLUSTERED_WITH=rabbit1   
  ports:
    - "5674:5672"
